# Generated by Django 3.2.8 on 2021-11-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='espera_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='canales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
