# Generated by Django 3.2.8 on 2021-11-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0002_auto_20211102_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='longitud_cola',
            field=models.IntegerField(default=0),
        ),
    ]
