# Generated by Django 3.2.8 on 2021-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0003_sede_longitud_cola'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(default='default.svg', upload_to='upload/%y'),
        ),
    ]
