# Generated by Django 3.2.8 on 2021-11-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0004_sede_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(default='default.svg', upload_to='img/%y'),
        ),
    ]
