# Generated by Django 3.2.9 on 2021-11-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0005_alter_sede_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='abierta',
            new_name='habilitada',
        ),
    ]
