# Generated by Django 3.2.9 on 2021-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0007_auto_20211106_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='hora_fin',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='hora_inicio',
            field=models.TimeField(default=0),
        ),
    ]
