# Generated by Django 3.2.9 on 2021-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0008_auto_20211106_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
